version: '3'
services:
  app:
    build:
      context: .
      dockerfile: ./docker/golang/Dockerfile
    image: elaborate/backend
    container_name: elaborate-backend
    volumes:
      - ./:/go/src/Elaborate-backend
    ports:
      - "3000:3000"
