# TODO: 2.1のコマンド試すのできたらやりたい
version: 2
jobs:
  build:
    docker:
      # TODO: custom docker imageをpullできたらしたい
      - image: circleci/golang:1.11

    steps:
      - checkout

      - restore_cache:
          keys:
            - go-mod-v1-{{ checksum "go.sum" }}

      - run:
          name: Run test!
          command: GO_ENV=test go test -v ./...

      - save_cache:
          key: go-mod-v1-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
